### ISSUE TITLE
Important -Inaayat

### ISSUE THREAD

**Issue by Inaayat04** [xxAROX/SkinStealer#1]
My discord acc got disband idk why add my new discord 
Inaa#8014

**Comment by xxAROX** [comment]
oof

**Comment by xxAROX** [comment]
![grafik](https://user-images.githubusercontent.com/57589973/78759847-8c02f400-7980-11ea-96c2-1547f0cf64f1.png)
invalid name

**Comment by xxAROX** [comment]
@Inaayat04
